import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Navbar() {
  return (
    <nav className="w-full flex justify-between items-center py-4 px-8 bg-gradient-to-r from-blue-200 via-purple-200 to-pink-200 dark:from-gray-800 dark:via-gray-900 dark:to-gray-800 shadow-md mb-8 rounded-b-xl">
      <div className="font-bold text-lg tracking-tight text-blue-800 dark:text-blue-200 drop-shadow">
        Global Exp Tracker
      </div>
      <div className="flex gap-6">
        <Link
          href="/"
          className="hover:underline underline-offset-4 text-blue-800 dark:text-blue-200 font-medium transition-colors"
        >
          Home
        </Link>
        <Link
          href="/groups"
          className="hover:underline underline-offset-4 text-purple-800 dark:text-purple-200 font-medium transition-colors"
        >
          Groups
        </Link>
        <Link
          href="/about"
          className="hover:underline underline-offset-4 text-pink-800 dark:text-pink-200 font-medium transition-colors"
        >
          About
        </Link>
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-full bg-gradient-to-br from-blue-100 via-purple-100 to-pink-100 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
